// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: proto/anomaly_detection.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AnomalyRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Timestamp        string                 `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Level            string                 `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`
	Component        string                 `protobuf:"bytes,3,opt,name=component,proto3" json:"component,omitempty"`
	Message          string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	MessageLength    int32                  `protobuf:"varint,5,opt,name=message_length,json=messageLength,proto3" json:"message_length,omitempty"`
	HasErrorKeywords int32                  `protobuf:"varint,6,opt,name=has_error_keywords,json=hasErrorKeywords,proto3" json:"has_error_keywords,omitempty"`
	Hour             int32                  `protobuf:"varint,7,opt,name=hour,proto3" json:"hour,omitempty"`
	DayOfWeek        int32                  `protobuf:"varint,8,opt,name=day_of_week,json=dayOfWeek,proto3" json:"day_of_week,omitempty"`
	IsWeekend        int32                  `protobuf:"varint,9,opt,name=is_weekend,json=isWeekend,proto3" json:"is_weekend,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AnomalyRequest) Reset() {
	*x = AnomalyRequest{}
	mi := &file_proto_anomaly_detection_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnomalyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnomalyRequest) ProtoMessage() {}

func (x *AnomalyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_anomaly_detection_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnomalyRequest.ProtoReflect.Descriptor instead.
func (*AnomalyRequest) Descriptor() ([]byte, []int) {
	return file_proto_anomaly_detection_proto_rawDescGZIP(), []int{0}
}

func (x *AnomalyRequest) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *AnomalyRequest) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *AnomalyRequest) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

func (x *AnomalyRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AnomalyRequest) GetMessageLength() int32 {
	if x != nil {
		return x.MessageLength
	}
	return 0
}

func (x *AnomalyRequest) GetHasErrorKeywords() int32 {
	if x != nil {
		return x.HasErrorKeywords
	}
	return 0
}

func (x *AnomalyRequest) GetHour() int32 {
	if x != nil {
		return x.Hour
	}
	return 0
}

func (x *AnomalyRequest) GetDayOfWeek() int32 {
	if x != nil {
		return x.DayOfWeek
	}
	return 0
}

func (x *AnomalyRequest) GetIsWeekend() int32 {
	if x != nil {
		return x.IsWeekend
	}
	return 0
}

type AnomalyResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AnomalyScore   float64                `protobuf:"fixed64,1,opt,name=anomaly_score,json=anomalyScore,proto3" json:"anomaly_score,omitempty"`
	IsAnomaly      bool                   `protobuf:"varint,2,opt,name=is_anomaly,json=isAnomaly,proto3" json:"is_anomaly,omitempty"`
	OriginalLog    string                 `protobuf:"bytes,3,opt,name=original_log,json=originalLog,proto3" json:"original_log,omitempty"`
	Recommendation string                 `protobuf:"bytes,4,opt,name=recommendation,proto3" json:"recommendation,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AnomalyResponse) Reset() {
	*x = AnomalyResponse{}
	mi := &file_proto_anomaly_detection_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnomalyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnomalyResponse) ProtoMessage() {}

func (x *AnomalyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_anomaly_detection_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnomalyResponse.ProtoReflect.Descriptor instead.
func (*AnomalyResponse) Descriptor() ([]byte, []int) {
	return file_proto_anomaly_detection_proto_rawDescGZIP(), []int{1}
}

func (x *AnomalyResponse) GetAnomalyScore() float64 {
	if x != nil {
		return x.AnomalyScore
	}
	return 0
}

func (x *AnomalyResponse) GetIsAnomaly() bool {
	if x != nil {
		return x.IsAnomaly
	}
	return false
}

func (x *AnomalyResponse) GetOriginalLog() string {
	if x != nil {
		return x.OriginalLog
	}
	return ""
}

func (x *AnomalyResponse) GetRecommendation() string {
	if x != nil {
		return x.Recommendation
	}
	return ""
}

var File_proto_anomaly_detection_proto protoreflect.FileDescriptor

const file_proto_anomaly_detection_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/anomaly_detection.proto\x12\x10anomalydetection\"\xa4\x02\n" +
	"\x0eAnomalyRequest\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\tR\ttimestamp\x12\x14\n" +
	"\x05level\x18\x02 \x01(\tR\x05level\x12\x1c\n" +
	"\tcomponent\x18\x03 \x01(\tR\tcomponent\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12%\n" +
	"\x0emessage_length\x18\x05 \x01(\x05R\rmessageLength\x12,\n" +
	"\x12has_error_keywords\x18\x06 \x01(\x05R\x10hasErrorKeywords\x12\x12\n" +
	"\x04hour\x18\a \x01(\x05R\x04hour\x12\x1e\n" +
	"\vday_of_week\x18\b \x01(\x05R\tdayOfWeek\x12\x1d\n" +
	"\n" +
	"is_weekend\x18\t \x01(\x05R\tisWeekend\"\xa0\x01\n" +
	"\x0fAnomalyResponse\x12#\n" +
	"\ranomaly_score\x18\x01 \x01(\x01R\fanomalyScore\x12\x1d\n" +
	"\n" +
	"is_anomaly\x18\x02 \x01(\bR\tisAnomaly\x12!\n" +
	"\foriginal_log\x18\x03 \x01(\tR\voriginalLog\x12&\n" +
	"\x0erecommendation\x18\x04 \x01(\tR\x0erecommendation2\xc8\x01\n" +
	"\x10AnomalyDetection\x12T\n" +
	"\rDetectAnomaly\x12 .anomalydetection.AnomalyRequest\x1a!.anomalydetection.AnomalyResponse\x12^\n" +
	"\x13StreamDetectAnomaly\x12 .anomalydetection.AnomalyRequest\x1a!.anomalydetection.AnomalyResponse(\x010\x01B\tZ\a./protob\x06proto3"

var (
	file_proto_anomaly_detection_proto_rawDescOnce sync.Once
	file_proto_anomaly_detection_proto_rawDescData []byte
)

func file_proto_anomaly_detection_proto_rawDescGZIP() []byte {
	file_proto_anomaly_detection_proto_rawDescOnce.Do(func() {
		file_proto_anomaly_detection_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_anomaly_detection_proto_rawDesc), len(file_proto_anomaly_detection_proto_rawDesc)))
	})
	return file_proto_anomaly_detection_proto_rawDescData
}

var file_proto_anomaly_detection_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_anomaly_detection_proto_goTypes = []any{
	(*AnomalyRequest)(nil),  // 0: anomalydetection.AnomalyRequest
	(*AnomalyResponse)(nil), // 1: anomalydetection.AnomalyResponse
}
var file_proto_anomaly_detection_proto_depIdxs = []int32{
	0, // 0: anomalydetection.AnomalyDetection.DetectAnomaly:input_type -> anomalydetection.AnomalyRequest
	0, // 1: anomalydetection.AnomalyDetection.StreamDetectAnomaly:input_type -> anomalydetection.AnomalyRequest
	1, // 2: anomalydetection.AnomalyDetection.DetectAnomaly:output_type -> anomalydetection.AnomalyResponse
	1, // 3: anomalydetection.AnomalyDetection.StreamDetectAnomaly:output_type -> anomalydetection.AnomalyResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_anomaly_detection_proto_init() }
func file_proto_anomaly_detection_proto_init() {
	if File_proto_anomaly_detection_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_anomaly_detection_proto_rawDesc), len(file_proto_anomaly_detection_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_anomaly_detection_proto_goTypes,
		DependencyIndexes: file_proto_anomaly_detection_proto_depIdxs,
		MessageInfos:      file_proto_anomaly_detection_proto_msgTypes,
	}.Build()
	File_proto_anomaly_detection_proto = out.File
	file_proto_anomaly_detection_proto_goTypes = nil
	file_proto_anomaly_detection_proto_depIdxs = nil
}
